# Generated by Django 5.2.5 on 2025-08-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='product_size',
            field=models.FloatField(),
        ),
    ]
